//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Areana
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Game_ID { get; set; }
        public string Game_Full_Name { get; set; }
        public string Game_Short_Name { get; set; }
        public Nullable<System.DateTime> Release_Date { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> Upload_Date { get; set; }
        public string Game_Type { get; set; }
        public int Min_Spc_ID { get; set; }
        public int Rec_Spc_ID { get; set; }
        public string Primary_Comment { get; set; }
        public string Warnings { get; set; }
        public string Developer_Comment_1 { get; set; }
        public string Developer_Comment_2 { get; set; }
    
        public virtual Game_Images Game_Images { get; set; }
        public virtual Specification Min_Spc { get; set; }
        public virtual Specification Rec_Spc { get; set; }
        public virtual Specifications_Technical Tech_Spc { get; set; }
    }
}
