//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Areana
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Images
    {
        public int Game_ID { get; set; }
        public byte[] Large_Image_1 { get; set; }
        public byte[] Large_Image_2 { get; set; }
        public byte[] Large_Image_3 { get; set; }
        public byte[] Large_Image_4 { get; set; }
        public byte[] Small_Image { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
