//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Areana
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        public Specification()
        {
            this.Min_Games = new HashSet<Game>();
            this.Rec_Games = new HashSet<Game>();
        }
    
        public int Specification_ID { get; set; }
        public string OS { get; set; }
        public string Processor { get; set; }
        public string Memory { get; set; }
        public string Graphics { get; set; }
        public string DirectX { get; set; }
        public string Storage { get; set; }
        public string Sound_Card { get; set; }
    
        public virtual ICollection<Game> Min_Games { get; set; }
        public virtual ICollection<Game> Rec_Games { get; set; }
    }
}
