//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Areana
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specifications_Technical
    {
        public int Game_ID { get; set; }
        public string Game_Version { get; set; }
        public string Interface_Language { get; set; }
        public string Audio_Language { get; set; }
        public string Uploader { get; set; }
        public string Game_File_Name { get; set; }
        public string Game_Download_Size { get; set; }
        public string MDSSUM { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
